# Generated by Django 5.0.4 on 2024-05-12 22:08

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='номер главы')),
                ('name', models.CharField(max_length=64, verbose_name='название главы')),
                ('introduction', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='введение')),
            ],
            options={
                'verbose_name': 'глава',
                'verbose_name_plural': 'главы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название раздела')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_basics_app.chapter')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_basics_app.chapter')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128, verbose_name='вопрос')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_basics_app.test')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
