# Generated by Django 5.0.4 on 2024-05-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_basics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='ответ')),
                ('is_right', models.BooleanField(default=False, verbose_name='он правильный?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_basics_app.question')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
            },
        ),
    ]
