# Generated by Django 5.0.4 on 2024-05-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_basics_app', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='url_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='url имя'),
        ),
    ]
