# Generated by Django 5.0.4 on 2024-05-13 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_basics_app', '0004_remove_chapter_introduction_remove_chapter_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='название главы'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='url_name',
            field=models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='url имя'),
        ),
    ]
