# Generated by Django 5.0.4 on 2024-05-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid_basics_app', '0005_chapter_created_at_alter_chapter_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
