# Generated by Django 5.0.4 on 2024-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_basics_app', '0006_delete_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'Выбор'), (2, 'Текст')], default=1, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=128, verbose_name='текстовый ответ'),
        ),
    ]
