# Generated by Django 5.0.4 on 2024-05-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_basics_app', '0007_question_type_alter_answer_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=128, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Одиночный выбор'), (1, 'Множественный выбор'), (2, 'Текст')], default=0, verbose_name='Тип вопроса'),
        ),
    ]
