# Generated by Django 5.0.4 on 2024-05-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_basics_app', '0009_remove_chapter_created_at_chapter_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.TextField(verbose_name='вопрос'),
        ),
    ]
