# Generated by Django 5.0.4 on 2024-05-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_basics_app', '0010_alter_question_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(max_length=128, verbose_name='вопрос'),
        ),
    ]
